### ISSUE TITLE
Typo in ESPArto.h

### ISSUE THREAD

**Issue by uherting** [philbowles/esparto#11]
in ESPArto.h it reads '#include "pintypes.h"' but it should be rather #include "pinTypes.h" with a capital 'T'.
I found the typo while compiling ESPArto's example program A_HelloWorld.ino after adding the required libs ESPArto, ESPAsyncUDP, ESP Async WebServer, and PubSubClient to platformio.ini .

**Comment by philbowles** [comment]
thanks!

**Comment by philbowles** [comment]
Will be fixed shortly in v3.0.3. - thanks again

**Comment by uherting** [comment]
As far as I can remember /ESPArto.h was corrected . Currently src/ESPArto.h still contains the typo.
