### ISSUE TITLE
NTP Issues 2

### ISSUE THREAD

**Issue by Braehead** [philbowles/esparto#18]
The TZ in the GUI and code needs re-working:

1) It should be renamed to 'Offset' as it does not accept ISO8601 zone names.

2) It should take positive and negative hours and minutes, not just integer hours.  Places like Nepal are +4 hours and +45 minutes ahead of GMT/UTC and can't be entered currently.

3) Need to make it clear that Esparto NTP does not support Summer/Winter time adjustments (currently) either.

**Comment by philbowles** [comment]
1. Fair point. All "_TZ" replaced by _OFFSET in v3.3.1 and webUI changed to match
2. I hear ya. Not a lot I can do till espressif fix this: https://github.com/esp8266/Arduino/issues/5823 Hopefully not too many folk from partial time zones will have a problem, if they do I shall refer them to the above link to exert pressure. Till then...
2a negative values already work - were you making a general point , or did you have a specific issue? 
![Capture](https://user-images.githubusercontent.com/27769598/61363711-c7a2de80-a884-11e9-9a86-3fc4b52ac6ac.JPG)
3. Again, fair point. I will adjust the documentation. I have no plans to add this. My view is that it's a small ask to manually change the offset 2x per year vs the complication and effort of adding it.

Once again thanks for your diligence and support.

**Comment by Braehead** [comment]
Thanks for the update.

2a) Was just a general point.

3) Agreed that it would be a huge amount of code to support this and not practical in the space of an ESP8266.  But it should be noted in documentation.  The user should code their own if and as needed.

Does the fix mentioned in [https://github.com/esp8266/Arduino/pull/5828](url) work?  It says its merged as of 1Mar.
