### ISSUE TITLE
Duplicate NTP Declaration

### ISSUE THREAD

**Issue by Braehead** [philbowles/esparto#20]
Getting a duplicated declaration since last NTP changes:

ESPARTO_NTP_OFFSET

Declared in line 118 & 141 of esparto.h

**Comment by philbowles** [comment]
Yep. My bad. Rushing things. Can you try it gain and close issue if its all ok?

**Comment by Braehead** [comment]
Yes this appears to operating correctly now.  The ConfigBlock is correctly altering the NTP settings.
