### ISSUE TITLE
undefined reference to SmartPins::spPins

### ISSUE THREAD

**Issue by narfel** [philbowles/esparto#4]
Hi Phil,
any idea what this is about? Looks like my compiler can't link smartpins.
.pioenvs\d1_mini_lite\libd23\libSmartPins.a(SmartPins.cpp.o):(.text._ZN9SmartPins10isSmartPinEh[_ZN9SmartPins10isSmartPinEh]+0x0): undefined reference to `SmartPins::spPins'

In SmartPins.cpp there are several declarations for SmartPins::SP_PIN SmartPins::spPins[]={...
I am trying to build in platformio, Arduino IDE doesn't throw that error.

**Comment by philbowles** [comment]
Ah...never used platformio _ I'll have a look though

**Comment by philbowles** [comment]
Doh, never even got to looking - dawned on me: Arduino IDE makes a number of external defines (-D...) in call to compiler to define the board etc. SmartPins uses this to decide which set of hardware pin definitions to bring in. Obviously platformio either does it differently or not at all. I will put this on my "back burner" list as the "main" target was Arduino IDE. IF (big IF) I can get it compatible with platfromio easily as well, then I will give it a shot, but dont hold your breath!

**Comment by philbowles** [comment]
I will leave this "open" till I have had a chance to look at platformio

**Comment by narfel** [comment]
That sounds like an awful lot of work for a out of target problem. Thanks anyway, pio atom/vscode is powerful though, worth a look in any case. Thanks for the reply.

**Comment by kebasaa** [comment]
Hi, I'm having the same problem when trying to compile for Wemos D1 mini Pro. No clue why. So to check, I simply compiled for Wemos D1 mini (the normal version), and then it worked. So is this some sort of definition problem in smartPins? Can you add the Wemos D1 mini Pro (for versions 1.0.0 and v1.1.0, I guess going with a copy of the D1 mini's hardware definition is good enough)

**Comment by narfel** [comment]
Its not a definition problem, it's a implementation problem. The Arduino IDE does handle external defines [differently](https://docs.platformio.org/en/latest/projectconf/section_env_build.html) than the Arduino IDE.

**Comment by kebasaa** [comment]
Oh ok. Well in that case, I'll just compile for the D1 mini and be happy that it works.

**Comment by vertex-github** [comment]
Also hit this.  To make this work, add the correct ```build_flags``` to your ```platformio.ini``` file:

I'm using the Wemos D1 Mini:
```
[env:d1_mini]
platform = espressif8266
lib_extra_dirs = ~/Documents/Arduino/libraries
board = d1_mini
framework = arduino
lib_ldf_mode = deep+
build_flags = -D ARDUINO_ESP8266_WEMOS_D1MINI
```

This #define is being referenced in ```SmartPins.cpp``` - look in there for your correct board definition (there are a bunch of other board types defined in there).  Since I'm also using an Adafruit library that needs ```<SPI.h>``` I also had to add ```ib_ldf_mode = deep+` to make the imports work.

**Comment by narfel** [comment]
Wow, that was easy. Thanks vertex! I just compiled a sample with pio in vsc. I'll have a play when i find some time.
