### ISSUE TITLE
Documentation a bit sparse

### ISSUE THREAD

**Issue by kebasaa** [philbowles/esparto#8]
Hi, thanks so much for creating Esparto, it's such a cool piece of software. However, I'm struggling a bit with the documentation. It seems that the examples don't explain enough, so for example, I'm not sure how to use some of the functions. Would it be possible to list the available functions and what they do?

Let me give you 2 examples that I struggle with:
- I want to grab sensor data off i2c and send it through MQTT, but I have not clue how. The examples don't make it clear how to publish on MQTT.
- I want to use an ultrasonic sensor (HC-SR04) with Esparto. It's triggered through the same pin as it's read. Trigger happens by pulling the pin high for 10 uS, and then I want to set an interrupt to see how much time passed between triggering and the interrupt (which is a function of distance). And then I need to repeat that. But how do I change the pin modes over and over again?

**Comment by aapris** [comment]
I've just
```
void setupHardware() {
  Serial.begin(115200);
  Wire.begin();
  init_bh1750();  // initialises sensor and checks that it is available
  simple=Esparto.every(1000, read_bh1750);     
}
```
And in `read_bh1750` something like this:

```
void read_bh1750() {
  uint16_t lux = bh1750.readLightLevel();
  Esparto.publish("bh1750/lux", lux);
}
```
This seems to work, though I'm not sure is this the best way to implement such sensor reading.

**Comment by kebasaa** [comment]
Nice, thanks! I wish that was in the examples.
